name: Build Unity

on: [pull_request]

jobs:
  buildForAllSupportedPlatforms:
    name: Build ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
          - WebGL # WebGL.
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - name: Caching Unity Library
        uses: actions/cache@v2
        with:
          path: integrations/Unity/simulate-unity/Library
          key: Library-Simulate
          restore-keys: |
            Library-Simulate-
            Library-

      - name: Build Unity Simulate
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: integrations/Unity/simulate-unity
          buildsPath: integrations/Unity/simulate-unity/builds

      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: integrations/Unity/simulate-unity/builds/${{ matrix.targetPlatform }}
